/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AssignmentManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author BN GAMING
 */
public class AddCourse extends javax.swing.JFrame {
    private int StudentEnrollment;
private boolean isCourseCodeSelected = false;

    /**
     * Creates new form AddStudent
     */
    public AddCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseTeacher = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        txtCourseCredits = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCourseTeacherEnroll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jButton13.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton13.setText("Main Menu");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/cropadmin-removebg3003030.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 274));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Course Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 29, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Teacher:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 67, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Credits");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 146, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Code:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 108, 90, -1));

        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 29, 305, -1));

        txtCourseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 67, 305, -1));

        txtCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 105, 305, -1));

        txtCourseCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseCreditsActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 143, 305, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Admin Option Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 292, 200, 49));

        jButton14.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton14.setText("Main Menu");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 359, 200, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton2.setText("Add LAB Course ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 292, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton3.setText("Add Theory Course ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 292, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("CourseTeacherEnrollment:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 201, -1, -1));
        getContentPane().add(txtCourseTeacherEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 203, 305, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/blubgfull.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 870, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTeacherActionPerformed

    private void txtCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCodeActionPerformed

    private void txtCourseCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCreditsActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminOptions AO = new AdminOptions();
       AO.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              String courseName = txtCourseName.getText();
    String courseTeacher = txtCourseTeacher.getText();
    String courseCode = txtCourseCode.getText();
    int courseCredit = Integer.parseInt(txtCourseCredits.getText());
    int courseTeacherEnroll = Integer.parseInt(txtCourseTeacherEnroll.getText());
    Course courseObj = new Course(courseName, courseTeacher, courseCode, courseCredit, courseTeacherEnroll);

    // Check if the course code already exists
    if (isCourseCodeSelected) {
        JOptionPane.showMessageDialog(null, "Course with the same code already selected");
        return; // Exit the method without adding the course
    }

    try {
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

        // Check if the teacher name and teacher enrollment exist in the TD table
        String teacherSearchSql = "SELECT * FROM TD WHERE Enrollment = ?";
        PreparedStatement teacherSearchPst = con.prepareStatement(teacherSearchSql);
        teacherSearchPst.setInt(1, courseTeacherEnroll);
        ResultSet teacherSearchRs = teacherSearchPst.executeQuery();

        if (teacherSearchRs.next()) {
            // Teacher found, add the course
            String sq1 = "INSERT INTO CD1 (CourseName, CourseTeacher, CourseCode, CourseCredit, CourseMarks, CourseTeacherEnroll) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sq1);
            pst.setString(1, courseObj.getCourseName());
            pst.setString(2, courseObj.getCourseTeacher());
            pst.setString(3, courseObj.getCourseCode());
            pst.setInt(4, courseObj.getCourseCredit());
            pst.setInt(5, courseObj.getLabassignmentmarks());
            pst.setInt(6, courseObj.getCourseTeacherEnroll());

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                // Course added successfully
                isCourseCodeSelected = true; // Set the flag to indicate a course with the same code has been selected
                JOptionPane.showMessageDialog(null, "Course added successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add course teacher enroll not found");
            }

            pst.close();
        } else {
            // Teacher not found
            JOptionPane.showMessageDialog(null, "Teacher not found with the enrollment");
        }

        teacherSearchRs.close();
        teacherSearchPst.close();
        con.close();
    } catch (Exception e) {
        System.out.println(e);
    } 



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String courseName = txtCourseName.getText();
    String courseTeacher = txtCourseTeacher.getText();
    String courseCode = txtCourseCode.getText();
    int courseCredit = Integer.parseInt(txtCourseCredits.getText());
    int courseTeacherEnroll = Integer.parseInt(txtCourseTeacherEnroll.getText());
    Course courseObj = new Course(courseName, courseTeacher, courseCode, courseCredit, courseTeacherEnroll);

    // Check if the course code already exists
    if (isCourseCodeSelected) {
        JOptionPane.showMessageDialog(null, "Course with the same code already selected");
        return; // Exit the method without adding the course
    }

    try {
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

        // Check if the teacher name and teacher enrollment exist in the TD table
        String teacherSearchSql = "SELECT * FROM TD WHERE Enrollment = ?";
        PreparedStatement teacherSearchPst = con.prepareStatement(teacherSearchSql);
        teacherSearchPst.setInt(1, courseTeacherEnroll);
        ResultSet teacherSearchRs = teacherSearchPst.executeQuery();

        if (teacherSearchRs.next()) {
            // Teacher found, add the course
            String sq1 = "INSERT INTO CD1 (CourseName, CourseTeacher, CourseCode, CourseCredit, CourseMarks, CourseTeacherEnroll) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sq1);
            pst.setString(1, courseObj.getCourseName());
            pst.setString(2, courseObj.getCourseTeacher());
            pst.setString(3, courseObj.getCourseCode());
            pst.setInt(4, courseObj.getCourseCredit());
            pst.setInt(5, courseObj.getTheoryassignmnetmarks());
            pst.setInt(6, courseObj.getCourseTeacherEnroll());

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                // Course added successfully
                isCourseCodeSelected = true; // Set the flag to indicate a course with the same code has been selected
                JOptionPane.showMessageDialog(null, "Course added successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add course teacher enroll not found");
            }

            pst.close();
        } else {
            // Teacher not found
            JOptionPane.showMessageDialog(null, "Teacher not found with the enrollment");
        }

        teacherSearchRs.close();
        teacherSearchPst.close();
        con.close();
    } catch (Exception e) {
        System.out.println(e);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseCredits;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseTeacher;
    private javax.swing.JTextField txtCourseTeacherEnroll;
    // End of variables declaration//GEN-END:variables
}
