/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AssignmentManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ABC
 */
public class DeleteStudent extends javax.swing.JFrame {

    /**
     * Creates new form DeleteStudent
     */
    public DeleteStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCourseOutput = new javax.swing.JTextArea();
        searchstudent = new javax.swing.JTextField();
        deletestud = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Delete Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, 171, 38));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Enter Enrollment");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtCourseOutput.setColumns(20);
        txtCourseOutput.setRows(5);
        jScrollPane1.setViewportView(txtCourseOutput);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 565, 230));

        searchstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchstudentActionPerformed(evt);
            }
        });
        getContentPane().add(searchstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 122, 110, -1));

        deletestud.setBackground(new java.awt.Color(102, 0, 153));
        deletestud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletestud.setForeground(new java.awt.Color(204, 204, 255));
        deletestud.setText("Search for delete");
        deletestud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudActionPerformed(evt);
            }
        });
        getContentPane().add(deletestud, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 172, 274, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("searched results found:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 227, -1, -1));

        jLabel4.setText("jxzjxzj");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 21, -1, 66));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/red3601908.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchstudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchstudentActionPerformed

    private void deletestudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudActionPerformed
        // TODO add your handling code here:
        
         String enrollment = searchstudent.getText();

    try {
                       dbconnection db = new dbconnection();


        String selectQuery = "SELECT Name, Age, Address, Cnic, Enrollment, Section, Semester, Password FROM std1 WHERE Enrollment = ?";
        PreparedStatement selectPst = db.getCon().prepareStatement(selectQuery);
        selectPst.setString(1, enrollment); 
    ResultSet rs = selectPst.executeQuery();


        if (rs.next()) {
            String name = rs.getString("Name");
            int age = rs.getInt("Age");
            String address = rs.getString("Address");
            String cnic = rs.getString("Cnic");
            String section = rs.getString("Section");
int sem = rs.getInt("Semester");
String password = rs.getString("Password");

            txtCourseOutput.setText("Name: " + name + "\n" +
                                    "Age: " + age + "\n" +
                                    "Address: " + address + "\n" +
                                    "CNIC: " + cnic + "\n" +
                                    "Enrollment: " + enrollment + "\n" +
                                    "Section: " + section + "\n" +
                                    "Semester: " + sem + "\n" +
                                    "Password: " + password);

            // Ask for confirmation before deleting the student
            int confirmDelete = JOptionPane.showConfirmDialog(this, "Do you want to delete this student?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmDelete == JOptionPane.YES_OPTION) {
                String deleteQuery = "DELETE FROM std1 WHERE Enrollment = ?";
            PreparedStatement deletePst = db.getCon().prepareStatement(deleteQuery);
                deletePst.setString(1, enrollment);
                int rowsAffected = deletePst.executeUpdate();
                if (rowsAffected > 0) {
                    txtCourseOutput.setText("Student with Enrollment " + enrollment + " deleted successfully.");
                } else {
                    txtCourseOutput.setText("Enrollment not found. No student deleted.");
                }
                deletePst.close();
            }
        } else {
            txtCourseOutput.setText("No record found for the given Enrollment.");
        }

        rs.close();
    selectPst.close();
    db.closeConnection();
    } catch (Exception e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_deletestudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletestud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchstudent;
    private javax.swing.JTextArea txtCourseOutput;
    // End of variables declaration//GEN-END:variables
}
