/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AssignmentManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BN GAMING
 */
public class StudentOptions extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public StudentOptions(){
    
    }
    public String Enrollment;
    public String StudentName;
    public StudentOptions(String Enrollment,String StudentName) {
        initComponents();
        this.Enrollment=Enrollment;
        this.StudentName=StudentName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputname = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txtEnrollCourseCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel7.setText("See Course Marks:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/transparentbbooks.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 620, 480));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setText("Student Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 0, -1, 41));

        txtOutput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtOutputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(txtOutput);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 350, 220));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Student Enrollment:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 59, -1, -1));

        txtLogin.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        txtLogin.setText("Enter");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 401, 133, -1));

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        coursetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CourseName", "CourseTeacher", "CourseCode", "CourseCredit", "CourseMarks"
            }
        ));
        coursetable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                coursetableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(coursetable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 220, 538, 107));

        jTextPane1.setEditable(false);
        jTextPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 59, 132, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel4.setText("Welcome! ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 31, -1, -1));

        outputname.setEditable(false);
        outputname.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                outputnameAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(outputname);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 31, 146, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setText("Enter Course Code:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 368, -1, -1));
        getContentPane().add(txtEnrollCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 370, 195, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/blubgfull.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 740));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 560, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
String EnrollCourseCode = txtEnrollCourseCode.getText();

try {
    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

    // Connection to the first database
    Connection con1 = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");
    String sql = "SELECT CourseName, CourseTeacher, CourseCode, CourseCredit, CourseMarks,CourseTeacherEnroll FROM CD1 WHERE CourseCode = ?";
    PreparedStatement pst = con1.prepareStatement(sql);
    pst.setString(1, EnrollCourseCode);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String courseName = rs.getString("CourseName");
        String courseTeacher = rs.getString("CourseTeacher");
        String courseCode = rs.getString("CourseCode");
        int courseCredit = rs.getInt("CourseCredit");
        int courseMarks = rs.getInt("CourseMarks");
        int courseTeacherEnroll = rs.getInt("CourseTeacherEnroll");

        // Connection to the second database
        Connection con2 = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

        // Check if the record already exists in the "SC" table
        String selectSql = "SELECT * FROM SC WHERE StudentEnroll = ? AND CourseCode = ?";
        PreparedStatement selectPst = con2.prepareStatement(selectSql);
        selectPst.setString(1, Enrollment); // Assuming Enrollment is the variable containing the student enrollment value
        selectPst.setString(2, courseCode);

        ResultSet selectRs = selectPst.executeQuery();

        if (selectRs.next()) {
            JOptionPane.showMessageDialog(null,"Student already enrolled in this course.");
        } else {
            // Insert course details into the second database
            String insertSql = "INSERT INTO SC (StudentName, StudentEnroll, CourseName, CourseCode,MarksObtained,CourseMarks, CourseTeacher,CourseTeacherEnroll) VALUES (?, ?, ?, ?, ?, ?,?,?)";
            PreparedStatement insertPst = con2.prepareStatement(insertSql);
            insertPst.setString(1, StudentName);
            insertPst.setString(2, Enrollment);
            insertPst.setString(3, courseName);
            insertPst.setString(4, courseCode);
            insertPst.setString(5, null);
            insertPst.setInt(6, courseMarks);
            insertPst.setString(7, courseTeacher);
            insertPst.setInt(8, courseTeacherEnroll);

            // Execute the insert statement
            insertPst.executeUpdate();

            JOptionPane.showMessageDialog(null,"Student Enrolled !!");
            insertPst.close();
        }

        // Close the select result set and statement
        selectRs.close();
        selectPst.close();

        // Close the second database connection
        con2.close();
    }

    // Close the first database result set, statement, and connection
    rs.close();
    pst.close();
    con1.close();
} catch (ClassNotFoundException e) {
    // Handle ClassNotFoundException
    e.printStackTrace();
} catch (SQLException e) {
    // Handle SQLException
    e.printStackTrace();
}



  
    
    
        
        
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void coursetableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_coursetableAncestorAdded
   try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

            String sql = "SELECT CourseName, CourseTeacher, CourseCode, CourseCredit,CourseMarks FROM cd1";
            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
                    DefaultTableModel dt=(DefaultTableModel)coursetable.getModel();

            dt.setRowCount(0);
            while (rs.next()) {

                    String name = rs.getString("CourseName");
                    String tea = rs.getString("CourseTeacher");
                    
                    String code=rs.getString("CourseCode");
                          int hrs = rs.getInt("CourseCredit");
                          int marks=rs.getInt("CourseMarks")

                ;

               //  retrieved data to the table model
          Object tbdata[] = {name, tea, code, hrs,marks};

            
            dt.addRow(tbdata);
            }

            rs.close();

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_coursetableAncestorAdded

    private void jTextPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextPane1AncestorAdded
       jTextPane1.setText(Enrollment);
    }//GEN-LAST:event_jTextPane1AncestorAdded

    private void outputnameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_outputnameAncestorAdded
       outputname.setText(StudentName);
    }//GEN-LAST:event_outputnameAncestorAdded

    private void jLabel6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel6AncestorAdded
   
    
    }//GEN-LAST:event_jLabel6AncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  StringBuilder studentData = new StringBuilder();

try {
    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

    Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

    String studentEnroll = Enrollment;

    String sql = "SELECT * FROM SC WHERE StudentEnroll = ?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, studentEnroll);

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {
        String studentName = rs.getString("StudentName");
        String courseName = rs.getString("CourseName");
        String courseCode = rs.getString("CourseCode");
        String marksObtained = rs.getString("MarksObtained");

        studentData.append("Student Enrollment: ").append(studentEnroll).append("\n");
        studentData.append("Student Name: ").append(studentName).append("\n");
        studentData.append("Course Name: ").append(courseName).append("\n");
        studentData.append("Course Code: ").append(courseCode).append("\n");
        studentData.append("Marks Obtained: ").append(marksObtained).append("\n\n");
        studentData.append("-------------------------------------------").append("\n\n");
    }

    if (studentData.length() == 0) {
        studentData.append("No record found for StudentEnroll: ").append(studentEnroll).append("\n");
    }

    rs.close();
    pst.close();
    con.close();
} catch (ClassNotFoundException e) {
    e.printStackTrace();
} catch (SQLException e) {
    e.printStackTrace();
}

// Use the studentData StringBuilder as needed
// Example: display the data in a label
txtOutput.setText(studentData.toString());


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtOutputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtOutputAncestorAdded


    }//GEN-LAST:event_txtOutputAncestorAdded

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable coursetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane outputname;
    private javax.swing.JTextField txtEnrollCourseCode;
    private javax.swing.JButton txtLogin;
    private javax.swing.JTextPane txtOutput;
    // End of variables declaration//GEN-END:variables
}
