/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AssignmentManagement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BN GAMING
 */
public class TeacherOption extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    String TeacherName;
    int Enrollment;
    public TeacherOption(int Enrollment,String TeacherName) {
        initComponents();
        this.Enrollment=Enrollment;
        this.TeacherName=TeacherName;
    }

    private TeacherOption() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentEnrollment = new javax.swing.JTextField();
        txtLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtStudentObtainedMarks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnameoutput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtenrolloutput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtOutput1 = new javax.swing.JTextPane();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txtOutput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtOutputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(txtOutput);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 350, 460));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 480, 510));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setText("Teacher Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Student Enrollment:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 121, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Obtained Marks:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 164, 140, -1));
        getContentPane().add(txtStudentEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 121, 173, -1));

        txtLogin.setText("Enter Marks");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 92, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 565, -1, -1));

        txtStudentObtainedMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentObtainedMarksActionPerformed(evt);
            }
        });
        getContentPane().add(txtStudentObtainedMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 161, 173, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 32, -1, -1));

        txtnameoutput.setEditable(false);
        txtnameoutput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtnameoutputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtnameoutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameoutputActionPerformed(evt);
            }
        });
        getContentPane().add(txtnameoutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 34, 99, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel6.setText("Enrollment:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 32, -1, -1));

        txtenrolloutput.setEditable(false);
        txtenrolloutput.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtenrolloutputAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txtenrolloutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 34, 109, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/blubgfull.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 1110, 670));

        txtOutput1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtOutput1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(txtOutput1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 350, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        int studentEnrollment = Integer.parseInt(txtStudentEnrollment.getText());
int marksObtained = Integer.parseInt(txtStudentObtainedMarks.getText());

try {
    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
    Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");



    // Check if both teacher enrollment and student enrollment exist in the SC table
    String searchSql = "SELECT * FROM SC WHERE StudentEnroll = ? AND CourseTeacherEnroll = ?";
    PreparedStatement searchPst = con.prepareStatement(searchSql);
    searchPst.setInt(1, studentEnrollment);
    searchPst.setInt(2, Enrollment);
    ResultSet searchRs = searchPst.executeQuery();

    if (searchRs.next()) {
        // Student and teacher enrollments found, update the marks obtained
        String updateSql = "UPDATE SC SET MarksObtained = ? WHERE StudentEnroll = ? AND CourseTeacherEnroll = ?";
        PreparedStatement updatePst = con.prepareStatement(updateSql);
        updatePst.setInt(1, marksObtained);
        updatePst.setInt(2, studentEnrollment);
        updatePst.setInt(3, Enrollment);

        int rowsAffected = updatePst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Marks updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update marks");
        }

        updatePst.close();
    } else {
        // Student and/or teacher enrollment not found
        JOptionPane.showMessageDialog(null, "Student and/or teacher enrollment not found in SC table");
    }

    searchRs.close();
    searchPst.close();
    con.close();
} catch (Exception e) {
    System.out.println(e);
}
        
        
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStudentObtainedMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentObtainedMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentObtainedMarksActionPerformed

    private void txtnameoutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameoutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameoutputActionPerformed

    private void txtnameoutputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtnameoutputAncestorAdded
txtnameoutput.setText(TeacherName);        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameoutputAncestorAdded

    private void txtenrolloutputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtenrolloutputAncestorAdded
txtenrolloutput.setText(String.valueOf(Enrollment));
       // TODO add your handling code here:
    }//GEN-LAST:event_txtenrolloutputAncestorAdded

    private void txtOutput1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtOutput1AncestorAdded

    }//GEN-LAST:event_txtOutput1AncestorAdded

    private void txtOutputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtOutputAncestorAdded

    }//GEN-LAST:event_txtOutputAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringBuilder studentData = new StringBuilder();

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

            Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

            int TeacherEnroll = Enrollment;

            String sql = "SELECT * FROM SC WHERE CourseTeacherEnroll = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, TeacherEnroll);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String studentEnroll = rs.getString("StudentEnroll");
                String studentName = rs.getString("StudentName");
                String courseName = rs.getString("CourseName");
                String courseCode = rs.getString("CourseCode");
                String marksObtained = rs.getString("MarksObtained");

                studentData.append("Student Enrollment: ").append(studentEnroll).append("\n");
                studentData.append("Student Name: ").append(studentName).append("\n");
                studentData.append("Course Name: ").append(courseName).append("\n");
                studentData.append("Course Code: ").append(courseCode).append("\n");
                studentData.append("Marks Obtained: ").append(marksObtained).append("\n\n");
                studentData.append("-------------------------------------------").append("\n\n");
            }

            if (studentData.length() == 0) {
                studentData.append("No Student Enrolled").append(TeacherEnroll).append("\n");
            }

            rs.close();
            pst.close();
            con.close();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Use the studentData StringBuilder as needed
        // Example: display the data in a label
        txtOutput.setText(studentData.toString());

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton txtLogin;
    private javax.swing.JTextPane txtOutput;
    private javax.swing.JTextPane txtOutput1;
    private javax.swing.JTextField txtStudentEnrollment;
    private javax.swing.JTextField txtStudentObtainedMarks;
    private javax.swing.JTextField txtenrolloutput;
    private javax.swing.JTextField txtnameoutput;
    // End of variables declaration//GEN-END:variables
}
