/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AssignmentManagement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author BN GAMING
 */
public class UpdateTeacher extends javax.swing.JFrame {
    private int StudentEnrollment;

    /**
     * Creates new form AddStudent
     */
    public UpdateTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        txtTeacherDepartment = new javax.swing.JTextField();
        txtTeacherCourseCode = new javax.swing.JTextField();
        txtTeacherEnrollment = new javax.swing.JTextField();
        txtTeacherSpecialization = new javax.swing.JTextField();
        txtTeacherExperience = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTeacherPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton13.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton13.setText("Main Menu");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/cropadmin-removebg3003030.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 274));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 29, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Department:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 102, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Course Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 206, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Enrollment:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 67, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Experience:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 164, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Specialization:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 133, 105, -1));

        txtTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 29, 301, -1));

        txtTeacherDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherDepartmentActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 102, 305, -1));

        txtTeacherCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherCourseCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 203, 240, -1));

        txtTeacherEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherEnrollmentActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 67, 305, -1));

        txtTeacherSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherSpecializationActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 133, 305, -1));

        txtTeacherExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherExperienceActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeacherExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 164, 305, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Admin Option Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 292, 200, 49));

        jButton14.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton14.setText("Main Menu");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 359, 200, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton2.setText("UpdateTeacher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 345, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 244, 90, -1));
        getContentPane().add(txtTeacherPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 241, 305, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 244, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/blubgfull.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 830, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherNameActionPerformed

    private void txtTeacherEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherEnrollmentActionPerformed

    private void txtTeacherSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherSpecializationActionPerformed

    private void txtTeacherExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherExperienceActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminOptions AO = new AdminOptions();
       AO.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String teacherName = txtTeacherName.getText();
String teacherDepartment = txtTeacherDepartment.getText();
int teacherEnrollment = Integer.parseInt(txtTeacherEnrollment.getText());
int teacherExperience = Integer.parseInt(txtTeacherExperience.getText());
String teacherCourseCode = txtTeacherCourseCode.getText();
String teacherSpecialization = txtTeacherSpecialization.getText();
String teacherPassword = txtTeacherPassword.getText();

Faculty facultyObj = new Faculty(teacherName,teacherEnrollment, teacherDepartment, teacherSpecialization, teacherExperience);


try {           dbconnection db = new dbconnection();

    String searchSq1 = "SELECT * FROM TD WHERE Enrollment = ?";
        PreparedStatement searchPst = db.getCon().prepareStatement(searchSq1);
    searchPst.setInt(1, teacherEnrollment);
    ResultSet searchRs = searchPst.executeQuery();

    if (searchRs.next()) {

        String updateSql = "UPDATE TD SET Name=?, Department=?, Specialization=?, YearsOfExperience=?, TeacherCourseCode=?, Password=? WHERE Enrollment=?";
        PreparedStatement pst = db.getCon().prepareStatement(updateSql);
        pst.setString(1, facultyObj.getName());
        pst.setString(2, facultyObj.getDepartment());
        pst.setString(3, facultyObj.getSpecialization());
        pst.setInt(4, facultyObj.getYearsOfExperience());

        pst.setString(6, teacherPassword);
        pst.setInt(7, facultyObj.getEnrollment());

        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Update successful");
        } else {
            JOptionPane.showMessageDialog(null, "Update failed");
        }

        pst.close();
    } else {
        // Record not found
        JOptionPane.showMessageDialog(null, "Record not found for the given Enrollment");
    }

    searchRs.close();
    searchPst.close();
    db.closeConnection();

} catch (Exception e) {
    System.out.println(e);
}


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTeacherCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherCourseCodeActionPerformed

    private void txtTeacherDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtTeacherCourseCode;
    private javax.swing.JTextField txtTeacherDepartment;
    private javax.swing.JTextField txtTeacherEnrollment;
    private javax.swing.JTextField txtTeacherExperience;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JPasswordField txtTeacherPassword;
    private javax.swing.JTextField txtTeacherSpecialization;
    // End of variables declaration//GEN-END:variables
}
