/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AssignmentManagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author BN GAMING
 */
public class UpdateCourse extends javax.swing.JFrame {
    private int StudentEnrollment;

    /**
     * Creates new form AddStudent
     */
    public UpdateCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseTeacher = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        txtCourseCredits = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCourseTeacherEnroll = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jButton13.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton13.setText("Main Menu");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/cropadmin-removebg3003030.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 274));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Course Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 29, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Teacher:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 67, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Credits");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 146, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Code:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 108, 90, -1));

        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 29, 305, -1));

        txtCourseTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 67, 305, -1));

        txtCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 105, 305, -1));

        txtCourseCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseCreditsActionPerformed(evt);
            }
        });
        getContentPane().add(txtCourseCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 143, 305, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton1.setText("Admin Option Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 292, 200, 49));

        jButton14.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton14.setText("Main Menu");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 359, 200, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton2.setText("Add LAB Course ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 292, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jButton3.setText("Add Theory Course ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 292, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("CourseTeacherEnrollment:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 201, -1, -1));
        getContentPane().add(txtCourseTeacherEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 203, 305, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AssignmentManagement/blubgfull.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 940, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCourseTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTeacherActionPerformed

    private void txtCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCodeActionPerformed

    private void txtCourseCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseCreditsActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mainmenu mainmenuobj=new mainmenu();
        mainmenuobj.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminOptions AO = new AdminOptions();
       AO.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String CourseName = txtCourseName.getText();
        String CourseTeacher = txtCourseTeacher.getText();
        String CourseCode = txtCourseCode.getText();
        int CourseCredit = Integer.parseInt(txtCourseCredits.getText());
        int CourseTeacherEnroll = Integer.parseInt(txtCourseCredits.getText());
        Course CO=new Course(CourseName,CourseTeacher,CourseCode,CourseCredit,CourseTeacherEnroll);
        try {
           dbconnection db = new dbconnection();
            String sq1 = "INSERT INTO CD1( CourseName,CourseTeacher, CourseCode,CourseCredit,CourseMarks,CourseTeacherEnroll) VALUES (?,?,?,?,?,?)";
        PreparedStatement pst = db.getCon().prepareStatement(sq1);
            pst.setString(1,CO.getCourseName());
          pst.setString(2, CO.getCourseTeacher());

            pst.setString(3, CO.getCourseCode());
            pst.setInt(4, CO.getCourseCredit());

            pst.setInt(5, CO.getLabassignmentmarks());
            pst.setInt(6, CO.getCourseTeacherEnroll());
            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, " Course added succesfully");
            } else {
                JOptionPane.showMessageDialog(null, " failed");
            }
            pst.close();
        } catch (Exception e) {
            System.out.println(e);
      }  



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String courseName = txtCourseName.getText();
String courseTeacher = txtCourseTeacher.getText();
String courseCode = txtCourseCode.getText();
int courseCredit = Integer.parseInt(txtCourseCredits.getText());
int courseTeacherEnroll = Integer.parseInt(txtCourseTeacherEnroll.getText());
Course courseObj = new Course(courseName, courseTeacher, courseCode, courseCredit, courseTeacherEnroll);

try {
    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
    Connection con = DriverManager.getConnection("jdbc:ucanaccess://studentinfo1.accdb");

    // Check if the teacher name and teacher enrollment exist in the TD table
    String teacherSearchSql = "SELECT * FROM TD WHERE Name = ? AND Enrollment = ?";
    PreparedStatement teacherSearchPst = con.prepareStatement(teacherSearchSql);
    teacherSearchPst.setString(1, courseTeacher);
    teacherSearchPst.setInt(2, courseTeacherEnroll);
    ResultSet teacherSearchRs = teacherSearchPst.executeQuery();

    if (teacherSearchRs.next()) {
        // Teacher found, add the course
        String sql = "INSERT INTO CD1 (CourseName, CourseTeacher, CourseCode, CourseCredit, CourseMarks, CourseTeacherEnroll) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, courseObj.getCourseName());
        pst.setString(2, courseObj.getCourseTeacher());
        pst.setString(3, courseObj.getCourseCode());
        pst.setInt(4, courseObj.getCourseCredit());
        pst.setInt(5, courseObj.getTheoryassignmnetmarks());
        pst.setInt(6, courseObj.getCourseTeacherEnroll());

        int rowsAffected = pst.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Course added successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add course");
        }

        pst.close();
    } else {
        // Teacher not found
        JOptionPane.showMessageDialog(null, "Teacher not found with the given name and enrollment");
    }

    teacherSearchRs.close();
    teacherSearchPst.close();
    con.close();
} catch (Exception e) {
    System.out.println(e);
}

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtCourseCredits;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseTeacher;
    private javax.swing.JTextField txtCourseTeacherEnroll;
    // End of variables declaration//GEN-END:variables
}
